package com.github.oslokommune.oslonokkelen.kpc.model

/**
 * Identifies a keychain. This is generated by your application
 * and have to be unique within a keychain factory. The easiest
 * solution is probably to use an id you already have
 * (like a booking reference).
 */
data class KeychainId(val factoryId: KeychainFactoryId, val value: String) {
    init {
        Id.validate(value)
    }

    override fun toString(): String {
        return "${factoryId.value}/$value"
    }
}