name: Testing
on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: "Configure Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 16

      - name: "Gradle - Tests"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --no-watch-fs --parallel --stacktrace --max-workers=4


