name: Testing
on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions:
        contents: write

    steps:
      - uses: actions/checkout@v4

      - name: "Configure Java"
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 21

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4

      - name: "Gradle - Tests"
        run: ./gradlew test --no-watch-fs --parallel --stacktrace --max-workers=4


